# A script to make the metadata.csv file located in inst/extdata of the package.
# See ?AnnotationHubData::makeAnnotationHubMetadata for a description of the
# metadata.csv file, expected fields and data types. This
# AnnotationHubData::makeAnnotationHubMetadata() function can be used to
# validate the metadata.csv file before submitting the package.

library("here")
library("sessioninfo")


outdir <- "BSP2_files"
pkgname <- "HubBSP2"


meta <- data.frame(
    Title = "BSP2_RangedSummarizedExperiment_Gene",
    Description =
        "SummarizedExperiment object at the gene level for the BrainSEQ Phase II project generated by the Lieber Institute for Brain Development (LIBD) and available through the HubBSP2 Bioconductor package.",
    BiocVersion = "3.17",
    Genome = "GRCh38",
    SourceType = "GTF",
    SourceUrl = "https://bioconductor.org/packages/HubBSP2",
    SourceVersion = "Feb 17 2023",
    Species = "Homo sapiens",
    TaxonomyId = 9606,
    Coordinate_1_based = TRUE,
    DataProvider = "LIBD",
    Maintainer = "Leonardo Collado-Torres <lcolladotor@gmail.com>",
    RDataClass = "RangedSummarizedExperiment",
    DispatchClass = "Rda",
    RDataPath = file.path(
        pkgname,
        outdir,
        c(
            "BSP2_rse_gene_unfiltered.Rdata"
        )
    ),
    Tags = "BrainSEQ:BSP2:LIBD:brain:DLPFC:HPC",
    row.names = NULL,
    stringsAsFactors = FALSE
)

write.csv(
    meta,
    file = here::here("inst", "extdata", "metadata.csv"),
    row.names = FALSE
)

## Check
if (FALSE) {
    AnnotationHubData::makeAnnotationHubMetadata(here::here(), fileName = "metadata.csv")
}

## Reproducibility information
print("Reproducibility information:")
Sys.time()
proc.time()
options(width = 120)
session_info()
